spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://shopping-product
          predicates:
            - Path=/api/product/**,/hello,/index/catalog.json
          filters:
            - RewritePath=/api(?<segment>/?.*),$\{segment}
## http://localhost:88/api/product/category/list/tree
## http://shopping-product/product/category/list/tree

        - id: member_route
          uri: lb://shopping-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>/?.*),$\{segment}

        - id: third_party_route
          uri: lb://shopping-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://shopping-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>.*),/$\{segment}



        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*),/renren-fast/$\{segment}
## 前端项目，/api    http://localhost:8080/renren-fast/captcha.jpg?uuid=51e905d7-abb0-4ff2-8f9f-c372e3f7ccf7

